name: GitHub-Profile-Summary-Cards

on:
  # Execute the workflow every 24 hours
  schedule:
    - cron: "0 0 */1 * *" # Every 24 hours at midnight UTC
  # Allow manual triggering of the workflow
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate GitHub Profile Summary Cards
    permissions:
      contents: write

    steps:
      # Check out the repository
      - name: Check out repository
        uses: actions/checkout@v3

      # Generate GitHub profile summary cards
      - name: Generate GitHub profile summary cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN }}
        with:
          USERNAME: sahmedG # Specific GitHub username
          BRANCH_NAME: "main" # Branch where the cards will be pushed
          UTC_OFFSET: 3 # UTC offset for time adjustment
          EXCLUDE: "" # Exclude any specific stats if needed
          AUTO_PUSH: true # Automatically push the generated cards

      # Commit and push changes
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add profile-summary-card-output/
          git commit -m "Update GitHub profile summary cards"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN }}

